// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yunly.App.Crawler.HalifaxMyRec.Models;

namespace Yunly.App.Crawler.HalifaxMyRec.Migrations
{
    [DbContext(typeof(YunlyDbContext))]
    [Migration("20180802180507_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Yunly.App.Crawler.HalifaxMyRec.Models.RecProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvailableCapacity");

                    b.Property<bool?>("BlockBookingPayment");

                    b.Property<bool?>("DirectDebitPayment");

                    b.Property<string>("Instructor")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Language")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int?>("MaxAgeMonths");

                    b.Property<int?>("MinAgeMonths");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("NextSessionStartDate")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<DateTime?>("NextSessionStartDateFormatted")
                        .HasColumnType("datetime");

                    b.Property<bool?>("PaymentPlanAvailable");

                    b.Property<string>("PaymentPlanTemplateId")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int?>("ProgramId");

                    b.Property<int?>("RemainingSessions");

                    b.Property<int?>("SessionDurationMins");

                    b.Property<string>("StartDate")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<DateTime?>("StartDateFormatted")
                        .HasColumnType("datetime");

                    b.Property<int?>("TotalCapacity");

                    b.Property<int?>("TotalSessions");

                    b.Property<string>("WeekDays")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("WholeCourseBookingType");

                    b.HasKey("Id");

                    b.ToTable("RecProgram");
                });
#pragma warning restore 612, 618
        }
    }
}
